name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Lint (syntax)
        run: python -m py_compile cli.py core.py
      - name: Smoke test (dry-run then apply)
        run: |
          python cli.py examples/patch.md --dry-run
          python cli.py examples/patch.md --apply
          grep -q "Hello, WORLD!" examples/target.txt
          test -f examples/config.ini
