name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Lint (syntax)
        run: python -m py_compile cli.py core.py

      - name: Prepare examples (no trailing newline in target.txt)
        shell: bash
        run: |
          mkdir -p examples
          # <- sem newline no fim:
          printf "Hello, NAME!" > examples/target.txt
          # patch.md com fences intactas
          cat > examples/patch.md <<'MD'
